version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd frontend/react-app
      - npm install  # Install dependencies
  build:
    commands:
      - echo Building the React app...
      - npm run build  # Build the React app (this creates a 'build' folder)
  post_build:
    commands:
      - echo Build completed, deploying to S3...
      - aws s3 sync build/ s3://subdc.christiandirubbio.com/ --delete  # Sync the 'build' folder to the S3 bucket

artifacts:
  files:
    - '**/*'  # Include all files in the build folder
