version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd frontend/react-app
      - npm install 
  build:
    commands:
      - echo Building the React app...
      - npm run build 
  post_build:
    commands:
      - echo Build completed, deploying to S3...
artifacts:
  files:
    - build/**/*
