version: 0.2

phases:
  build:
    commands:
      -  cd ./backend/src
      -  ls
      -  aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO
      -  docker buildx build --platform linux/amd64 -t projects/subdc .
      -  docker tag projects/subdc:latest $ECR_REPO/projects/subdc:latest
      -  docker push $ECR_REPO/projects/subdc:latest                     
      -  aws ecs update-service --cluster $CLUSTER --service $SERVICE --force-new-deployment --region us-east-1
